"""empty message

Revision ID: 2c0356f59406
Revises: 3f60b39e89ba
Create Date: 2017-12-01 06:30:53.983694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c0356f59406'
down_revision = '3f60b39e89ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('country_geopol')
    op.drop_table('country_year_geopol')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country_year_geopol',
    sa.Column('country', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('country_code', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('gdp', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('population', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('life_expectancy', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('urbanization_percentage', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('per_capita_gdp', sa.REAL(), autoincrement=False, nullable=True)
    )
    op.create_table('country_geopol',
    sa.Column('country', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('continent', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('land_area', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('border_length', sa.REAL(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('country', name=u'country_geopol_pkey')
    )
    # ### end Alembic commands ###
